import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  researchSidebar: [
    "intro",
    // {
    //   type: "category",
    //   label: "Tutorial",
    //   items: ["tutorial-basics/create-a-document"],
    // },
  ],
  version1Sidebar: [
    "version1/project-design",
    "version1/project-structure",
    "version1/setup",
    // {
    //   type: "category",
    //   label: "Tutorial",
    //   items: ["tutorial-basics/create-a-document"],
    // },
  ],
  version2Sidebar: ["version2/project-design", "version2/setup"],
  version3Sidebar: ["version3/project-design"],
};

export default sidebars;
